[package]
name = "e_kor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = "0.6.4"
hmac = "0.12.1"
sha3 = "0.10.6"
k256 = "0.13.0"
num = "0.4.0"
hex = "0.4.3"